func foo() { throw ("err", 22) }
var e = try {
        foo()
    } catch {
        ("err", 22, 1) => false,
        ("err", 23) => false,
        ("err", 22) => true
    }